### ISSUE TITLE
ttk.Menubutton vs direction

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#126]
In ttk.Menubutton if I choose a direction other than the default, would it be possible to automatically change the arrow image to the same chosen direction? Or would it be possible to add this to ttk.bootstrap as a style (a style for each menu direction)?

`btn = ttk.Menubutton(self, text='Text', direction='above')`

See the image below, the menu opens upwards but the arrow image is downwards.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/3d8n34b/Menubutton.png" alt="Menubutton" border="0"></a >

direction options:
https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/ttk-Menubutton.html

**Comment by israel-dryer** [comment]
The menu widget itself isn't a themed widget. I've hacked the legacy widgets a bit by adding callbacks to update the styles in various places so that they behave more like ttk widgets. But, those types of changes are limited. The only way to do something like this would be to create your own custom menu widget. Similar to what I posted here https://github.com/israel-dryer/ttkbootstrap/issues/127#issuecomment-1008146094
