### ISSUE TITLE
ScrolledFrame Behavior

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#140]
Is this a bug or expected behavior?

This code generates this layout:
```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledFrame

class MainFrame(ttk.Window):
    def __init__(self):
        ttk.Window.__init__(self)

        self.geometry('500x300')
        self.title('Tkinter')
        
        self.set_notebook()
        self.set_tab0()
        return

    def set_notebook(self):
        self.nb = ttk.Notebook(self)
        self.nb.place(relx=0, rely=0, relwidth=1, relheight=1)
        return

    def set_tab0(self):
        #self.frm = ScrolledFrame(self, autohide=True)
        self.frm = ttk.Frame(self)
        self.frm.place(relx=0, rely=0, relwidth=1, relheight=1)

        ##Top
        self.frm_top = ttk.Frame(self.frm)
        self.frm_top.pack(fill=BOTH, expand=1)

        ttk.Label(self.frm_top, text='frame 1: top place (10, 25)').place(x=10, y=25)
        
        ttk.Label(self.frm_top, text='frame 1: top pack').pack()

        #middle
        self.frm_middle = ttk.Frame(self.frm)
        self.frm_middle.pack(fill=BOTH, expand=1)

        ttk.Label(self.frm_middle, text='frame 2: middle - pack').pack()

        ttk.Label(self.frm_middle, text='frame 2: middle - place (10, 25)').place(x=10, y=25)

        #Bottom
        self.frm_bottom = ttk.Frame(self.frm)
        self.frm_bottom.pack(side=BOTTOM, fill=X)
        ttk.Label(self.frm_bottom, text='frame 3: bottom - pack').pack()

        #self.nb.add(self.frm.container, text='Test')
        self.nb.add(self.frm, text='Test')
        return

if __name__== '__main__':
    app = MainFrame()
    app.mainloop()
```
<img src="https://i.ibb.co/qWvz53Z/nromal.png" alt="nromal" border="0">

----------------
Scrolled:

If I replace the frame (self.frm) with a ScrolledFrame, see how the layout changes: the widget with .place was not displayed and the frame side=bottom does not obey the bottom position:

<img src="https://i.ibb.co/wLJ9V7H/scrolled.png" alt="scrolled" border="0">

```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledFrame

class MainFrame(ttk.Window):
    def __init__(self):
        ttk.Window.__init__(self)

        self.geometry('500x300')
        self.title('Tkinter')
        
        self.set_notebook()
        self.set_tab0()
        return

    def set_notebook(self):
        self.nb = ttk.Notebook(self)
        self.nb.place(relx=0, rely=0, relwidth=1, relheight=1)
        return

    def set_tab0(self):
        self.frm = ScrolledFrame(self, autohide=True)
        #self.frm = ttk.Frame(self)
        self.frm.place(relx=0, rely=0, relwidth=1, relheight=1)

        ##Top
        self.frm_top = ttk.Frame(self.frm)
        self.frm_top.pack(fill=BOTH, expand=1)

        ttk.Label(self.frm_top, text='frame 1: top place (10, 25)').place(x=10, y=25)
        
        ttk.Label(self.frm_top, text='frame 1: top pack').pack()

        #middle
        self.frm_middle = ttk.Frame(self.frm)
        self.frm_middle.pack(fill=BOTH, expand=1)

        ttk.Label(self.frm_middle, text='frame 2: middle - pack').pack()

        ttk.Label(self.frm_middle, text='frame 2: middle - place (10, 25)').place(x=10, y=25)

        #Bottom
        self.frm_bottom = ttk.Frame(self.frm)
        self.frm_bottom.pack(side=BOTTOM, fill=X)
        ttk.Label(self.frm_bottom, text='frame 3: bottom - pack').pack()

        self.nb.add(self.frm.container, text='Test')
        #self.nb.add(self.frm, text='Test')
        return

if __name__== '__main__':
    app = MainFrame()
    app.mainloop()
```

**Comment by israel-dryer** [comment]
This may be related to the [issue when using pack and place together](https://stackoverflow.com/questions/29102568/tkinter-place-geometry-manager-not-working#:~:text=You%20should%20not%20mix%20Tkinter%20layout%20managers%3B%20use,in%20the%20constructor%2C%20or%20by%20using%20frame.place%2C%20e.g.). However, this gave me a clue of how to fix this, which I was partially implementing already. I just needed to assign a height as well as width so that the pack and place managers have a point of reference.  
 
<img width="569" alt="Code_sjyWy6qFHF" src="https://user-images.githubusercontent.com/42584742/149673671-f0fb5887-83d6-4ee2-8aef-460cbda7ad5e.png">

When doing this, I get this result.

<img width="502" alt="python_4T1obZHa3t" src="https://user-images.githubusercontent.com/42584742/149673653-7143a5cb-b35a-41d4-884e-449053e1b775.png">

Also, this line is not needed, and should probably be avoided as the frm no longer has control of the geometry when you [delegate it to the notebook](https://tcl.tk/man/tcl8.6/TkCmd/ttk_notebook.htm#M10).
```python
self.frm.place(relx=0, rely=0, relwidth=1, relheight=1)
```
Instead, you would use the `sticky` parameter when you add the frame:
```python
self.nb.add(self.frm.container, text='Test', sticky=NSEW)
```

Finally, a tip on using `Window`, you can actually assign the size and title in the constructor if you wish
```python
class MainFrame(ttk.Window):
    def __init__(self):
        ttk.Window.__init__(self, size=(500, 300), title="Tkinter")
```
I'll push a fix on this soon after I run a few more tests.

**Comment by israel-dryer** [comment]
@antrrax, confirm if you can that this fixes your issue. I was able to test it successfully on my end, but I want to make sure.

**Comment by antrrax** [comment]
I tested it with the same code as in the first post. At first the problem was solved.
Thanks for the quick resolution.

**Comment by israel-dryer** [comment]
@antrrax, the scrolled frame has a default width and height like the Canvas widget, however, you can override with pack, place, grid, just as with any other widget. 

I've added a new parameter called `scrollheight` which sets the height of the content frame manually in the case that you are using a relative positioning such as in the example above.

```python
self.frm = ScrolledFrame(self, autohide=True, scrollheight=300)
```
