### ISSUE TITLE
update standard tkinter widgets

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#16]
I had to remove most of the global styles that I applied to the standard tkinter widgets because it was interfering with my ttk styles. The solution is to use the `option_add` method to target specific legacy widgets. I've created a helper function to make this simpler... `StylerTk._set_option`.

For example...from within the StyleTk class:
```python
self._set_option('checkbutton.selectColor, self.theme.colors.primary)
```

You have to use the option database names... which tend to following the *camelCase* naming convention. But, they can be found in the TCL/TK Man pages. For example: https://www.tcl.tk/man/tcl8.7/TkCmd/checkbutton.htm

I've reviewed most of the legacy widget that directly affect the ttk widgets I'm using. However, I need to go back through these one at a time to make sure they look okay in case someone decides to use them. Not a high priority, however, as they are not the intended target for this package.

**Comment by PySimpleGUI** [comment]
When is 8.7 slated to be released with Python?  I didn't even know about it until I saw the link you posted.

**Comment by israel-dryer** [comment]
I've looked. I can't find anything though. I can't wait... 8.7 supports svg natively.

**Comment by PySimpleGUI** [comment]
If only tkinter was sufficiently separated from Python so that any version could be installed.  Doesn't seem like it's asking for much, but it is.  Linux seems to be able to do this, while Windows can't.  ActiveState provides (sells?) different versions of Python and tkinter combined than what you see on Python.org.  I don't think I'll be able to directly utilize many of the features except for additions like support for SVG where the APIs remain the same.

8.6.10 has been out on the Mac for a very long time, and it's still not in any of the non-Alpha windows versions.  I can't really use much right away other than to build in support in PySimpleGUIPlus where users **_may_** be able to add custom widgets.  The plan, for now, is that only 'User Elements" that are subclassed for existing elements will be supported first.

**Comment by israel-dryer** [comment]
So, the tk widgets aren't really the focus on this package, but I think I was able to get them to look ok with the primary colors for whatever theme is chosen. The other colors are available via the `colors` property for manual overrides.

![image](https://user-images.githubusercontent.com/42584742/114606260-143d6880-9c69-11eb-9ea4-0966cef66a18.png)

I have no idea how to remove the relief from the `spinbox`. None of the option database settings I tried worked. Also, I was not able to add any styles to the `Scrollbar`. However, since these are two widgets that are available in the ttk widget set, I don't really see this as an issue.

**Comment by israel-dryer** [comment]
> 
> 
> If only tkinter was sufficiently separated from Python so that any version could be installed. Doesn't seem like it's asking for much, but it is. Linux seems to be able to do this, while Windows can't. ActiveState provides (sells?) different versions of Python and tkinter combined than what you see on Python.org. I don't think I'll be able to directly utilize many of the features except for additions like support for SVG where the APIs remain the same.
> 
> 8.6.10 has been out on the Mac for a very long time, and it's still not in any of the non-Alpha windows versions. I can't really use much right away other than to build in support in PySimpleGUIPlus where users **_may_** be able to add custom widgets. The plan, for now, is that only 'User Elements" that are subclassed for existing elements will be supported first.

Unfortunately, if you installed an ActiveState version that supported a bunch of extra features, it probably wouldn't work for most people anyway right? Unless you could somehow bundle a newer version of tcl/tk with psg?

**Comment by daniilS** [comment]
Interesting, looks like buttonuprelief and buttondownrelief are indeed not working in tkinter.
