### ISSUE TITLE
ColorChoice and Colorchooser

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#161]
Linux Mint x64 Cinnamon 20.3 X11

In ColorChoice, when capturing the color, the taskbar disappears
example video:
https://www.mediafire.com/file/daurm26maz8worq/dropper.mp4/file

If you see in the video, although the bar is gone, the cursor continues to capture the color of the bar item

---

The tool tip also doesn't disappear when starting to capture the color

------

In the Colorchooser Dialog, the shortcut Ctrl+A (Select All) was not included (Entry e Spin buttons).
It is a very useful shortcut for the end user, it would be interesting to implement this.

**Comment by israel-dryer** [comment]
what is your screen resolution?

**Comment by israel-dryer** [comment]
Probably should update this too... the preview window should be vertically centered on the indicator x-axis, otherwise it becomes hard to see when at the bottom of the screen.

<img alt="python_DlObmzMApd" src="https://user-images.githubusercontent.com/42584742/150871950-e05d9a8c-a772-4610-9c0b-cc76347466d2.png">

**Comment by israel-dryer** [comment]
> Linux Mint x64 Cinnamon 20.3 X11
> 
> In ColorChoice, when capturing the color, the taskbar disappears example video: https://www.mediafire.com/file/daurm26maz8worq/dropper.mp4/file
> 
> If you see in the video, although the bar is gone, the cursor continues to capture the color of the bar item
> 
> The tool tip also doesn't disappear when starting to capture the color
> 
> In the Colorchooser Dialog, the shortcut Ctrl+A (Select All) was not included (Entry e Spin buttons). It is a very useful shortcut for the end user, it would be interesting to implement this.

This is very strange. The screenshot displayed in the background is obviously a  representation of the window because I can see the icons in the preview... however, as you say, it's not visible.

<img alt="nxplayer bin_byZIgcXeI5" src="https://user-images.githubusercontent.com/42584742/150873070-65c86f1a-dc80-4b1c-8c02-fab24a7e7914.png">

what should be happening is that a screenshot of the display is shown in a toplevel that is nearly transparent (can't be 100% transparent or it doesn't catch mouse events).

The location of the mouse on the screen is used to locate the coordinates of the clip to use in the preview window.

Will experiment and let you know.

**Comment by israel-dryer** [comment]
> Probably should update this too... the preview window should be vertically centered on the indicator x-axis, otherwise it becomes hard to see when at the bottom of the screen.
> 
> ![python_DlObmzMApd](https://user-images.githubusercontent.com/42584742/150871950-e05d9a8c-a772-4610-9c0b-cc76347466d2.png)

I see on Linux that it correctly prevents the preview from falling below view... not sure why this isn't working on Windows.

**Comment by israel-dryer** [comment]
If leave the alpha at 1.0 then it's fine. I remember there being a reason that I did not do that... I'll have to test it on Windows & Mac. Whatever the original reason was, it may no longer be valid.

<img width="637" alt="nxplayer bin_Uan81gSnlD" src="https://user-images.githubusercontent.com/42584742/150874349-7fc21f71-e39a-4081-985c-8e8268657ca6.png">

**Comment by antrrax** [comment]
Really, with alpha in 1.0 it worked here

**Comment by israel-dryer** [comment]
oh... I forgot... I didn't implement this for Mac OS. Too many hoops to jump through, including the user having to grant the app permission to record the screen. Lol.

**Comment by israel-dryer** [comment]
Ok, this tested OK on Windows 11 as well. 

The only problem is one that is already documented in the API, and that is if you try to use the dropper on a high definition screen without enabling HDPI support. This is done automatically for users who use the `ttkbootstrap.Window` class on Windows. However, those who are still using `tkinter.Tk()` will need to enable HDPI manually or will experience issues with the PIL.ImageGrab function not understand how to scale the image. I haven't test this on Linux with the high definition discrepancy, but I think this is probably a relatively small base of users that would be affected by the HDPI issue anyway (I hope).
