### ISSUE TITLE
Is there a way to define global fonts, such as family and size

### ISSUE THREAD

**Issue by funchan24** [israel-dryer/ttkbootstrap#205]
The font cannot be scaled. In some cases, the font is too small than the interface.

**Comment by israel-dryer** [comment]
Can you post an example of the issue?

**Comment by funchan24** [comment]
@israel-dryer The theme file of ttkbootstrap 0.5 contains font options, the file name is theme.json.

**Comment by israel-dryer** [comment]
Below is a simple example of how you would change the default font globally.

Would you mind posing this question in the Discussion forum, so that way the answer will be available to everyone.

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap import font

app = ttk.Window()

default_font = font.nametofont('TkDefaultFont')
default_font['size'] = 16

lbl = ttk.Label(text="Testing")
lbl.pack(padx=20, pady=20)

app.mainloop()import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap import font

app = ttk.Window()

default_font = font.nametofont('TkDefaultFont')
default_font['size'] = 16

lbl = ttk.Label(text="Testing")
lbl.pack(padx=20, pady=20)

app.mainloop()
```

The reason I took that option out of the Theme settings is because the fonts were too unpredictable on various operating systems.

**Comment by israel-dryer** [comment]
reopening until replaced by discussion post.
