### ISSUE TITLE
TableView wrong size after using build_table_data

### ISSUE THREAD

**Issue by JP2620** [israel-dryer/ttkbootstrap#218]
### Desktop (please complete the following information):

- ttkbootstrap 1.7.2
- OS: KDE neon User - 5.24 x86_64

### Describe the bug

- Using the function `build_table_data` when the tableview is not visible because of notebook's tabs makes it so that columns don't stretch (the default parameter in the `insert_column`). See the Partidos tab.
- Using the function `build_table_data` when the tableview is visible makes it so that the total width of the tableview is atleast the number of columns times 200px (again default parameter of `insert_column`), this can be corroborated by changing the width in the `conf.json` file and a screen ruler.

![bug](https://user-images.githubusercontent.com/44300242/156079382-f58c1cc6-4334-443b-8811-f527e392d372.gif)

![image](https://user-images.githubusercontent.com/44300242/156082890-5fb5d39b-9a78-43c6-ac52-c9ad76295526.png)

### To Reproduce

1. Clone https://github.com/JP2620/rating-tracker
2. Add a fourth column in the `standings_tv`, inside the `DataView` class, like in the code shown in the gif.
3. Add two players and then reproduce the sequence shown in the gif.

### Expected behavior

- The columns of the `matches_tv` should stretch after updating it with `build_table_data` when it is not visible.
- The `standings_tv` should look the same after updating it with `build_table_data` independently of its visibility.

### Additional context

- When pressing "Agregar Jugador", the tableview shown in the Partidos tabs is updated.
- When pressing "Guardar Resultado", both tableviews are updated.

**Comment by israel-dryer** [comment]
Sorry, I've been traveling a lot the last month and haven't had time to get to this one. I just wanted to let you know it's on my radar to look into.

**Comment by israel-dryer** [comment]
@JP2620, I think you can resolve this by using the TableView a bit differently. Currently, you are using the `build_table_data` method, which completely rebuilds the table from scratch. Instead, since you are essentially just clearing the table each time, it would be better for you to setup the columns in your constructor... just add the coldata to the object you are creating already in the constructor, and then set the column alignment there as well. This only needs to be done once.

```python
self.matches_tv = Tableview(matches_frame, 
    searchable=True, 
    height=13,
    autofit=True,
    coldata=[
        {"text": "Jugador 1", "stretch": True},
        {"text": "Resultado", "width": 100},
        {"text": "Jugador 2", "stretch": True},
    ]
)
self.matches_tv.pack(fill=ttk.BOTH)

for column in self.matches_tv.get_columns():
    self.matches_tv.align_column_left(cid=column.cid)
```

Then, when you want to clear your table and update it with new data, you can use something like the following to perform this function... then you won't have to reformat the table every time you make an update.

```python
def update_matches(self, matches: List) -> None:
    self.matches_tv.delete_rows()
    self.matches_tv.insert_rows(ttk.END, matches)
    self.matches_tv.reset_table()
```
