### ISSUE TITLE
`Messagebox` minimizes window automatically on Linux

### ISSUE THREAD

**Issue by demberto** [israel-dryer/ttkbootstrap#236]
### Desktop (please complete the following information):

ttkbootstrap: 1.7.1
OS: Lubuntu 20.04 64-bit

### Describe the bug

Raising a `Messagebox` through one of its methods, automatically minimizes the parent/root window **as well as itself**. This behaviour is not exhibited on Windows.

### To Reproduce

```python
import ttkbootstrap as tk
from ttkbootstrap.dialogs import Messagebox

wnd = tk.Window()
Messagebox.show_error("", parent=wnd)
```

### Expected behavior

It shouldn't minimize itself or the window.

### Additional context

`tkinter`'s own `show_error` method doesn't cause this.

**Comment by israel-dryer** [comment]
@demberto, the `Window` object is hidden by default until explicitly run with `Window.mainloop()` or unless you call `deiconify` on the window. The reason for this behavior is so that the window will update with all of it's components before showing... this avoids showing the user all of the flashes of screen drawing, etc...

Because you've set `wnd` as the logical parent of the `Messagebox`, that is why it is hidden along with the window in this case.

You can also show the messagebox without specifying a parent if you wish.

**Comment by demberto** [comment]
I see what you mean, this code is what I ran in IDLE which has a slightly different behaviour with tkinter. `wnd` is put in mainloop the moment itis initialised. Removing the `parent` argument has the same effect. I found out this when I was testing my application [DyCall](https://github.com/demberto/DyCall). I also mentioned that this doesn't happen on Windows.

**Comment by laggykiller** [comment]
As mentioned, the behavior is weird on Linux. Here is a demo with a tkinter application I made:

Windows:
![demo-windows](https://user-images.githubusercontent.com/61652821/217806824-deaafe1d-5ccd-4af0-9ab0-ae4ef99d1f8a.png)

Linux:
![demo-linux](https://user-images.githubusercontent.com/61652821/217806841-ec047002-e1ae-4938-b49b-55d7dbb7fe98.png)

**Comment by laggykiller** [comment]
In `src/ttkbootstrap/dialogs/dialogs.py Dialog.build`:

```
    def build(self):
        """Build the dialog from settings"""

        # setup toplevel based on widowing system
        if self._winsys == "win32":
            self._toplevel = ttk.Toplevel(
                transient=self.master,
                title=self._title,
                resizable=(0, 0),
                minsize=(250, 15),
                iconify=True,
            )
        else:
            self._toplevel = ttk.Toplevel(
                transient=self.master,
                title=self._title,
                resizable=(0, 0),
                windowtype="dialog",
                iconify=True,
            )
    # Function continues below...
```
If I set `iconify=False`, the whole problem disappear (Nothing get minimized).

If I comment out `transient=self.master`, the messagebox started in minimized state.

**Comment by laggykiller** [comment]
Mystery solved. If `self._toplevel` is created with `iconify=True`, then execution is stuck until opening back the window. This is caused by `src/ttkbootstrap/window.py` `Window.__init__` and `Toplevel.__init__`:
```
# Function continue above...

if iconify:
    self.iconify()

# Function continues...

if alpha is not None:
    if self.winsys == 'x11':
        self.wait_visibility(self)
    self.attributes("-alpha", alpha)

# Function continue below...
```

Linux uses x11 display system. The Window/Toplevel was iconified before setting alpha, which causes `wait_visibility()` to get stuck until user open back the window. Hence, `deiconify()` in `src/ttkbootstrap/dialogs/dialogs Dialog.build` could not be called until user open back the window.

I don't see the use of `wait_visibility()`. I propose removing those checks such to solve this bug, or set `iconify=False` when creating dialog in Linux.
