### ISSUE TITLE
ttkbootstrap ScrolledText cannot redefine style state

### ISSUE THREAD

**Issue by YoLHQ** [israel-dryer/ttkbootstrap#237]
### Desktop (please complete the following information):

ttkbootstrap Version [e.g. 1.7.2]
OS: [e.g. Window10]

### Describe the bug

With the ScrolledText component, cannot redefine style state.
Run st.configure(state='disabled') and error _tkinter.TclError: unknown option "-state".
There is no such problem with ScrolledText in Tkinter

**Comment by israel-dryer** [comment]
@YoLHQ, are you trying to disable text entry?

**Comment by israel-dryer** [comment]
@YoLHQ, you can access the text widget inside the ScrolledText by using the `text` property.

```python
st = ScrolledText()
st.text.configure(state='disabled')
```

**Comment by YoLHQ** [comment]
Thank you for your answer, which has helped me solve this problem.
st._text.configure(state="disabled")

**Comment by israel-dryer** [comment]
> Thank you for your answer, which has helped me solve this problem. st._text.configure(state="disabled")

I recommend using the `text` property rather than the private _text field. If the implementation of the _text field changes in the future it would break your code, but the `text` property will always be available.

https://github.com/israel-dryer/ttkbootstrap/blob/2a298e6a3d80f499da142d978ed298eb349c739e/src/ttkbootstrap/scrolled.py#L140
