### ISSUE TITLE
ScrolledFrame scrolling doesn't work with LabelFrame

### ISSUE THREAD

**Issue by atban98** [israel-dryer/ttkbootstrap#257]
### Desktop (please complete the following information):

ttkbootstrap Version 1.7.4
OS: Windows 10

### Describe the bug

When there is a `LabelFrame` in a `ScrolledFrame`, the scrolling doesn't work when the mouse is over the `LabelFrame`. The frame gets scrolled when the mouse is outside the `LabelFrame`.

### To Reproduce

Reproducer:
```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledFrame

app = ttk.Window()

sf = ScrolledFrame(app, autohide=True)
sf.pack(fill=BOTH, expand=YES, padx=10, pady=10)
lf = ttk.LabelFrame(sf)
lf.pack()
# add a large number of checkbuttons into the scrolled frame
for x in range(20):
    ttk.Checkbutton(lf, text=f"Checkbutton {x}").pack(anchor=W)

app.mainloop()
```

**Comment by israel-dryer** [comment]
@atban98, currently the children of the LabelFrame are catching the mousewheel events. It looks like the issue is that I'm only applying the mousewheel binding to the [immediate children of the ScrolledFrame](https://github.com/israel-dryer/ttkbootstrap/blob/2a298e6a3d80f499da142d978ed298eb349c739e/src/ttkbootstrap/scrolled.py#L377). In order for the binding to work on nested widget containers, I would need to recursively identify the children, grandchildren, etc... of the ScrolledFrame. I will need to do some testing and experimentation on this. I have a solution in mind, but I want to make sure that I don't create another problem while solving for this Russian doll scenario. :-)
