### ISSUE TITLE
Pressing ENTER when MessageBox.askyesno is displayed defaults to No but Yes is highlighted

### ISSUE THREAD

**Issue by AngeloKalpakis** [israel-dryer/ttkbootstrap#260]
### Desktop (please complete the following information):

- Windows 10
- Bootstrap 1.7.4
- Python 3.9.12
![image](https://user-images.githubusercontent.com/67386835/164068536-ce4a55fb-d0c0-45c5-8837-94a131993852.png)

### Describe the bug

When the MessageBox dialog is displayed to the user, the Yes option is highlighted. If the user presses the ENTER key, the No option is executed. Code is as follows:

if Messagebox.yesno('Are you sure you want to put the POS into Training Mode?', title='Warning', parent=self) == 'Yes':
    # Not executed is <Enter> or <Return> is pressed
    print('Selected YES')
else:
   print('Selected NO')

### Screenshots

![image](https://user-images.githubusercontent.com/67386835/164069389-f325ab2e-db03-4477-bc8e-d8f87de04c02.png)

**Comment by israel-dryer** [comment]
Ok, this is interesting. Apparently the default behavior in tkinter/tcl is that the space key activates the button. So, in order to get the desired behavior, I need to remove the space key binding at the class level and then apply a return key binding to the same class.

I also need to comment out a line in my base class so keep it from interfering with these changes. I'll post the by this weekend. In the meantime, feel free to use the space key. :-)

**Comment by AngeloKalpakis** [comment]
Excellent. Appreciate your help and quick responses.
