### ISSUE TITLE
enter title of bug here

### ISSUE THREAD

**Issue by sunny9495-dev** [israel-dryer/ttkbootstrap#288]
### Desktop (please complete the following information):

1.7.6

### Describe the bug

Button style configuration changing the bootstyle to info

### To Reproduce

```
self.style = Style(theme='litera')
self.style.configure('my.TButton', font=('Arial', 12))
self.btn = ttk.Button(self.root, text="Start", bootstyle="success", command=self.start, style='my.TButton')
self.btn.place(x=50, y=10, height=40, width=70)
```

### Expected behavior

I have set bootstyle to success, but its going to default bootstyle

**Comment by israel-dryer** [comment]
to modify the success style, you have to subclass the existing ttkbootstrap style https://github.com/israel-dryer/ttkbootstrap/issues/132
```python
import ttkbootstrap as ttk

app = ttk.Window(themename='litera', size=(400, 300))

# subclass an existing style
app.style.configure('my.success.TButton', font=('Arial', 12))

# apply the style to the button
btn = ttk.Button(app, text='Start', style='my.success.TButton')

btn.pack(padx=20, pady=20)
app.mainloop()
```
The "bootstyle" is just a ttk style in the background... in this case `success.Button`.

You cannot use both a `bootstyle` and a `style` argument since they are trying to do the same thing.
