### ISSUE TITLE
Center window

### ISSUE THREAD

**Issue by oldmale** [israel-dryer/ttkbootstrap#307]
### Desktop (please complete the following information):

windows 10

### Describe the bug

When I use position_ Center () and place_ window_ Center (), when running, the window will flash from the default position in the upper left corner and move to the center of the screen, which seems to affect the experience. enter title of bug here

### Screenshots

![01](https://user-images.githubusercontent.com/70990942/177067897-2bf3a563-7e7b-4878-b116-3f705cf747a3.jpg)
![02](https://user-images.githubusercontent.com/70990942/177067892-9886ff2e-8e5b-4874-b109-ca46667414e5.jpg)
![03](https://user-images.githubusercontent.com/70990942/177067895-ca6436f1-c9eb-417d-9e86-5aa70470e4ab.jpg)

**Comment by israel-dryer** [comment]
this is not a bug, just a quirk of tkinter. When you instantiate a tk instance, the window is created instantly. So, any updates you make at that point will be to a window that is already created, which is why it flashes from the original position to the center.

On way you can get around this is to use the `withdraw` method to remove the window from the screen, build it out, and then use the `deiconify` method to show it again.

This isn't a perfect solution because `withdraw` has it's own side-effects, but let me know how it works for you.

```python
from ttkbootstrap import Window

app = Window(themename='superhero')
app.withdraw()
app.position_center()
app.deiconify()
app.mainloop()
```
