### ISSUE TITLE
Theme demo UI bug

### ISSUE THREAD

**Issue by MoGHenry** [israel-dryer/ttkbootstrap#484]
### Desktop (please complete the following information):

Version: 1.10.1

### Describe the bug

When try to run the ```python -m ttkbootstrap``` in terminal, the error will occur.

### To Reproduce

1. Go to Terminal
2. Run ```python -m ttkbootstrap```
3. See error

### Expected behavior

open the ttkbootstrap's theme demo UI

### Screenshots

![image](https://github.com/israel-dryer/ttkbootstrap/assets/84988222/0954c2ed-4bcf-45bb-9592-f3a8e3dd1209)

### Additional context

By changing the ```Image.CUBIC``` to ```Image.BICUBIC``` in line 856 in widgets.py will fix this issue

**Comment by ismaelink** [comment]
This is due to an incompatibility between ttkbootstrap and newer versions of the Pillow library. I'm not sure which operating system you are using, but to resolve this issue, follow these steps:

1. **Uninstall the Pillow library:**

      Example: 
          `pip uninstall pillow`

2. **Now reinstall the library, but specify a supported version:**

      Example:
          `pip install pillow==8.2.0`

3. **Finally, run:**
          `python3 -m ttkcreator`

I could have provided more specific instructions if you had provided information about your operating system.

I hope this helps resolve the issue :smile:.

**Comment by MoGHenry** [comment]
> This is due to an incompatibility between ttkbootstrap and newer versions of the Pillow library. I'm not sure what operating system you're using, but to resolve this issue on your machine, follow these steps:
> 
> 1. **Uninstall the Pillow library:**
> 
>       Example: 
>           `pip uninstall pillow`
> 
> 2. **Now reinstall the library, but specify a supported version:**
> 
>       Example:
>           `pip install pillow==8.2.0`
> 
> 3. **Finally, run:**
>           `python3 -m ttkcreator`
> 
> I could have provided more specific instructions if you had provided information about your operating system.
> 
> I hope this helps resolve the issue :smile:.

thanks for your reply, my os is Windows 11
