### ISSUE TITLE
The style disappeared

### ISSUE THREAD

**Issue by AccelYu** [israel-dryer/ttkbootstrap#86]
Hi!
I am using version1.0.When i bind event on a frame to modify style,the style disappear.
```
    def create_label_frame(self, row, col, name):
        label_frame = ttk.Labelframe(
            master=self.root,
            text=name,
            height=250,
            width=350,
            style='primary'
        )

        label_frame.bind("<Enter>", lambda e: label_frame.config(style='info.TLabelframe'))
        label_frame.bind("<Leave>", lambda e: label_frame.config(style='primary.TLabelframe'))

        label_frame.grid_propagate(0)
        label_frame.grid(row=row, column=col, padx=10, pady=10)
        return label_frame
```
![1](https://user-images.githubusercontent.com/64239154/144482938-d2747128-3efc-41c9-b176-a2ac62637fb6.png)
![2](https://user-images.githubusercontent.com/64239154/144482954-78e36bd9-7790-4c9a-9ea8-6ba45fea4cbb.png)

**Comment by israel-dryer** [comment]
Ok, a few things.

1. Make sure you are using keywords only in `bootstyle`. It looks like you are instantiating the widget with `style='primary'`. This won't cause an error, it just won't do anything.
2. You can use the `bootstyle` keywords **info** and **primary** in the binding to be consistent, but technically, you can use styles and keywords in the `bootstyle` parameter as I've shown.
3. It appears the reason this isn't work is that you are using the `config` variable, which is an alias for `configure`. It looks like I forgot to set that alias so that `config` works as well. I'll make sure to add that in the next push, but for now, you can use the full `configure` method name.

```python
import tkinter as tk
import ttkbootstrap as ttk

def create_label_frame(root, row, col, name):
    label_frame = ttk.Labelframe(
        master=root,
        text=name,
        height=250,
        width=350,
        bootstyle='primary'
    )

    label_frame.bind("<Enter>", lambda e: label_frame.configure(style='danger.TLabelframe'))
    label_frame.bind("<Leave>", lambda e: label_frame.configure(bootstyle='primary.TLabelframe'))

    label_frame.grid_propagate(0)
    label_frame.grid(row=row, column=col, padx=10, pady=10)
    return label_frame

root = tk.Tk()

lf = create_label_frame(root, 0, 0, 'MyFrame')
lf.pack()

root.mainloop()
```

![C1ykkwiBpE](https://user-images.githubusercontent.com/42584742/144491723-4d30da37-0358-4035-af9b-08a33f64b728.gif)

Another way to achieve something like this without binding is to configure the active state of the style

```python
style = ttk.Style()
style.map('primary.TLabelframe', 
    bordercolor=[('hover', style.colors.danger)],
)

```

**Comment by israel-dryer** [comment]
I've added `config` as an alias for `configure`. Let me know if you have any issues when you update .

[Check the commit here](https://github.com/israel-dryer/ttkbootstrap/commit/827a959726d0552ef7cab907faf4aec4256ba360)

**Comment by AccelYu** [comment]
Nice!The problem is solved.Thanks a lot.
