### ISSUE TITLE
Issue with resizing

### ISSUE THREAD

**Issue by ForeverLebowski** [israel-dryer/ttkbootstrap#88]
Hello 

First of i want to say thank you for this great library!

I am currently using the library to write an application where i know the screen size so I am using .place for placement and resizing. It is an application for a touch screen so i need the widgets to be a bit bigger than they would be on a computer screen. 

Everything has been going well until I attempted to uppgrade to 1.0 in order to use some of the new widgets, more specifically the ON/OFF toggle widget.  When trying to place and resize using:

```
#ON/OFF switch
label = Label(text="Include row numbers").place(x=x_placement, y=170)
Checkbutton(bootstyle="success-round-toggle").place(x=x_placement, y=190, width = 200, height = 80)
```

I get the following result 
![bugg](https://user-images.githubusercontent.com/31983309/144711280-17b0c89b-4c8a-47a6-a410-99be99e6ed13.PNG)

If i change the code to 

```
        #ON/OFF switch
        label = Label(text="Include row numbers").place(x=x_placement, y=180)
        Checkbutton(bootstyle="success-round-toggle").place(x=x_placement, y=190, width = 200, height = 80)
```

I get: 
![bugg2](https://user-images.githubusercontent.com/31983309/144711344-91295403-ff95-4565-aece-e21d7b2f8cdf.PNG)

So seems like the actual bounding box(not sure about the terminology) is resizing but not the widget.

**Comment by israel-dryer** [comment]
I'll have to think about this one. The toggle is an image. There is a way for me to set the grow regions so that tkinter will replicate the regions to"expand" the image, but I'll need to see if I can do that with a complicated image like the toggle. I'll have to experiment with this approach though.

Another idea is that I recently added some functionality to enable scaling for high dpi screens so that the images correctly render in 2k and 4k.

You could try using this function in your application to enlarge the images. 

Are you using windows or Linux?

https://ttkbootstrap.readthedocs.io/en/latest/api/utility/

You can also call this directly from tcl/tk using `root.tk.call('tk', 'scaling', 2.0)`
after you've created your root window and before you create widgets.

**Comment by ForeverLebowski** [comment]
Thank you! The scaling was exactly what I wanted(saved me a lot of resizing of other widgets).

However I did have some interesting behavior with the enable_high_dpi_awareness(). I am running Windows and I tried to follow the docs and place the call before the root object like the docs said but did this not work. However when I placed the call after creating the root object per the instructions on Linux it worked perfectly.

**Comment by israel-dryer** [comment]
@ForeverLebowski, that's good to hear, glad it worked.

When you placed it before the root, did you use any arguments? Was there an error message?

**Comment by ForeverLebowski** [comment]
@israel-dryer I tried:

utility.enable_high_dpi_awareness(root=None, scaling=2.0)
utility.enable_high_dpi_awareness()

I did not get any error messages everything ran correctly there was just no change in the scaling.

**Comment by israel-dryer** [comment]
Ok. That actually makes sense based on how I have that function setup. Windows exposes a method through ctypes that enables high dpi awareness, which is one of the things that is called in the `enable_high_dpi_awareness` function. However, if this is called AFTER the window is created in windows, you end up with a titlebar that is drawn by the window manager that is not scaled the same as the rest of the window, and can look funny on 2k or 4k screens. I need to think about how to better implement this.

Thanks for the feedback.

**Comment by israel-dryer** [comment]
@ForeverLebowski, this issue inspired me to create a `Window` and `Toplevel` class that encapsulates a lot of the most common methods and attributes used by the `tkinter.Tk` and `tkinter.Toplevel` classes.

Check out the documentation here: https://ttkbootstrap.readthedocs.io/en/latest/api/window/window/

I included a **scaling** and **hdpi** parameter in the constructor, and also attached a `Style` property so that you do not have to create a style object.

Here's how the window would be created:
```python
import ttkbootstrap as ttk

app = ttk.Window(title="My Application", themename="superhero")
app.mainloop()
```

![image](https://user-images.githubusercontent.com/42584742/146708831-a8b8a011-f248-41b7-bad9-b81c74ddadd4.png)
