### ISSUE TITLE
Unable to resize rowheight in Treeview

### ISSUE THREAD

**Issue by vectar7** [israel-dryer/ttkbootstrap#99]
Hi,

When using ttkbootstrap, I'm unable to resize the rowheight in a Treeview. If I increase the font size, the rows just get cut off and I've been unable to get anything to work for resizing them. Any fix or work around for this? Thanks in advance!

See example:

```
from tkinter import *
from tkinter import ttk
from ttkbootstrap import Style

root = Tk()
root.geometry('600x600')

style = Style(theme='journal')

style.configure("Treeview.Heading", font=(None, 20), rowheight=40)
style.configure("Treeview", font=(None, 20), rowheight=40)

tv_apps = ttk.Treeview(
    root,
    columns=('Application', 'Status'),
    show='headings')

tv_apps.place(
    x = 50, y = 50,
    width = 450, height = 350)

tv_apps.heading('#1', text='Application')
tv_apps.column('#1', anchor='w')

tv_apps.heading('#2', text='Status')
tv_apps.column('#2', anchor='w')


tv_apps.insert('', 'end', values=('App1', 'Waiting'))
tv_apps.insert('', 'end', values=('App2', 'Working...'))        

if __name__ == '__main__':
    root.mainloop()
```

**Comment by israel-dryer** [comment]
@vectar7, which version of ttkbootstrap are you using?

**Comment by vectar7** [comment]
@israel-dryer I'm using version 1.1.0

**Comment by israel-dryer** [comment]
ok, I need to figure out why this is happening... but for now, a hack is to move the style configure AFTER the treeview is created.

```python
tv_apps = ttk.Treeview(
    root,
    columns=('Application', 'Status'),
    show='headings')

style.configure("Treeview.Heading", font=(None, 20), rowheight=40)
style.configure("Treeview", font=(None, 20), rowheight=40)
```

<img width="452" alt="image" src="https://user-images.githubusercontent.com/42584742/147377820-14646eb2-5fb0-4ad4-b72f-d3686f9408fb.png">


Thanks for pointing this out, I'll try to work on a permanent solution.

On another note, there is a `Window` class in 1.1 that allows you to simplify the code a bit.

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

# configure the window in the constructor
root = ttk.Window(title="Your App", size=(600, 600), themename="journal")

# the style object is already attached to the window
root.style.configure("Treeview.Heading", font="-size 20", rowheight=40)
root.style.configure("Treeview", font="-size 20", rowheight=40)

```

**Comment by vectar7** [comment]
Oh very nice. Thanks for the advice and the workaround! :)

**Comment by israel-dryer** [comment]
The root cause of this is that styles are created on-demand in ttkbootstrap 1.0+. When a style is used, it is registered with the Style object so that the style object knows not to attempt to create it again. Thus, until a style is actually used, it either does not exist, or ttkbootstrap does not know about it (in this case) and thus overwrites it with it's own default settings. This is why the code "works" when moving the style configure _after_ creating and using the default treeview style.

This also causes another side effect that I wish to fix, in that you cannot subclass a ttk class that does not exist yet, which is every style in ttkbootstrap until it is used in a widget.

The fix is override the `Style.configure` method so that it first checks for a ttkbootstrap style, and creates it if not already existing (this would include default styles such as "Treeview"). Then, the user's customizations will be applied to either the existing style or a subclassed version of it. The resulting behavior of `Style.configure` would then match the user's expectations while still maintaining the goal of not creating unused styles.
